# Changes here will be overwritten by Copier
_commit: 4.2.0
_src_path: https://github.com/DiamondLightSource/python-copier-template.git
author_email: ''
author_name: ''
component_lifecycle: experimental
component_owner: ''
component_type: service
description: ''
distribution_name: test
docker: false
docs_type: README
git_platform: github.com
github_org: DiamondLightSource
package_name: test
pypi: false
repo_name: test
strict_typing: true
type_checker: pyright
